name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-size: '20'
      - name: Install dependencies
        run: cd frontend && npm install
      - name: Lint and Build
        run: cd frontend && npm run lint && npm run build
